version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: mlarboul/flask_app:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://admin:admin@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/lib/postgresql/data

volumes:
  pgdata: {}